function compact(s){return String(s||"").toLowerCase().replace(/[^a-z0-9]/g,"")}
function walk(node,fn){if(!node||typeof node!=="object")return;if(Array.isArray(node)){node.forEach(n=>walk(n,fn));return}fn(node);Object.values(node).forEach(v=>{if(v&&typeof v==="object")walk(v,fn)})}
const STAT_META={passingYards:{cat:"passing",names:["passingyards","passingyds","netpassingyards"]},passingTouchdowns:{cat:"passing",names:["passingtouchdowns","passingtds"]},rushingYards:{cat:"rushing",names:["rushingyards","rushingyds"]},rushingTouchdowns:{cat:"rushing",names:["rushingtouchdowns","rushingtds"]},receivingYards:{cat:"receiving",names:["receivingyards","receivingyds"]},receptions:{cat:"receiving",names:["receptions"]},receivingTouchdowns:{cat:"receiving",names:["receivingtouchdowns","receivingtds"]}};
function namedValue(data,stat){const meta=STAT_META[stat],names=meta?meta.names.concat([compact(stat)]):[compact(stat)],cat=meta?.cat||"",hits=[];walk(data,obj=>{if(!Array.isArray(obj.stats))return;const catName=compact(obj.name||obj.displayName||obj.abbreviation),catOk=!cat||catName.includes(cat)||!catName;obj.stats.forEach(st=>{const n=compact(st.name||st.abbreviation||st.displayName);if(!names.includes(n)||!catOk)return;const v=Number(st.value??st.displayValue);if(!Number.isNaN(v))hits.push(v)})});if(hits.length)return hits[hits.length-1];walk(data,obj=>{const n=compact(obj.name||obj.displayName);if(!names.includes(n))return;const v=Number(obj.value??obj.displayValue);if(!Number.isNaN(v))hits.push(v)});return hits.length?hits[hits.length-1]:null}
function sumGamelog(data,stat){const meta=STAT_META[stat];if(!meta)return null;let total=0,used=false;walk(data,obj=>{const labels=obj.labels||obj.displayNames,events=obj.events;if(!Array.isArray(labels)||!Array.isArray(events))return;const l=labels.map(x=>String(x).toUpperCase());let idx=-1;if(stat==="passingYards")idx=l.indexOf("YDS");else if(stat==="passingTouchdowns")idx=l.indexOf("TD");else if(stat==="rushingYards"){const rush=Math.max(l.indexOf("CAR"),l.indexOf("RUSH"),l.indexOf("ATT"));idx=rush>=0?l.indexOf("YDS",rush):l.indexOf("YDS",1)}else if(stat==="rushingTouchdowns"){const first=l.indexOf("TD");idx=l.indexOf("TD",first+1);if(idx<0)idx=first}else if(stat==="receptions")idx=l.indexOf("REC");else if(stat==="receivingYards"){const rec=l.indexOf("REC");idx=rec>=0?l.indexOf("YDS",rec):l.lastIndexOf("YDS")}else if(stat==="receivingTouchdowns"){const rec=l.indexOf("REC");idx=rec>=0?l.indexOf("TD",rec):l.lastIndexOf("TD")}if(idx<0)return;events.forEach(ev=>{const stats=ev.stats||ev.athleteStats;if(!Array.isArray(stats)||stats[idx]==null)return;const v=Number(String(stats[idx]).replace(/[^0-9.+-]/g,""));if(!Number.isNaN(v)){total+=v;used=true}})});return used?total:null}
function idFromBlob(blob,sport){const text=typeof blob==="string"?blob:JSON.stringify(blob),nfl=[...text.matchAll(/espn\.com\/nfl\/player(?:\/stats)?\/_\/id\/(\d+)/g)].map(m=>m[1]);if((sport||"nfl")==="nfl"&&nfl.length)return nfl[0];const cfb=[...text.matchAll(/espn\.com\/college-football\/player(?:\/stats)?\/_\/id\/(\d+)/g)].map(m=>m[1]);return cfb[0]||nfl[0]||null}
/* Team ID: read only the athlete's own team object. (The old version walked the whole payload and grabbed the first object with an id+abbreviation, which was the news-category league {id:3080, abbreviation:"NFLFD"}.) */
function teamIdFromData(data){const t=data&&typeof data==="object"?(data.athlete&&data.athlete.team)||data.team:null;if(t&&typeof t==="object"&&!Array.isArray(t)&&t.id&&(t.abbreviation||t.displayName||t.location||t.nickname))return String(t.id);return null}
async function getJson(url){const r=await fetch(url);if(!r.ok)throw new Error(String(r.status));return r.json()}
async function resolveTeamId(path,athleteId){if(!athleteId)return null;for(const url of[`https://site.web.api.espn.com/apis/common/v3/sports/${path}/athletes/${athleteId}`,`https://site.api.espn.com/apis/common/v3/sports/${path}/athletes/${athleteId}`])try{const id=teamIdFromData(await getJson(url));if(id)return id}catch(_){}return null}
async function resolveAthleteId(bet){if(bet.espnAthleteId)return String(bet.espnAthleteId);const q=encodeURIComponent(bet.subject||"");for(const url of[`https://site.web.api.espn.com/apis/search/v2?query=${q}&limit=25`,`https://site.web.api.espn.com/apis/common/v3/search?query=${q}&limit=15`])try{const id=idFromBlob(await getJson(url),bet.sport);if(id)return id}catch(_){}return null}
async function teamGamesPlayed(sportPath,teamId,year){if(!teamId)return null;const hosts=typeof window!=="undefined"?["site.web.api.espn.com","site.api.espn.com"]:["site.api.espn.com","site.web.api.espn.com"],urls=hosts.flatMap(h=>[`https://${h}/apis/site/v2/sports/${sportPath}/teams/${teamId}/schedule?dates=${year}`,`https://${h}/apis/site/v2/sports/${sportPath}/teams/${teamId}/schedule`]);for(const url of urls)try{const data=await getJson(url),events=data.events||data.team?.events||[];const completed=events.filter(event=>{const status=event.status?.type||event.competitions?.[0]?.status?.type||{};return status.completed===true||["STATUS_FINAL","STATUS_FULL_TIME"].includes(status.name)}).length;if(completed>0)return completed}catch(_){}return null}
async function refreshPlayer(bet){if(!bet||bet.kind==="award"||!bet.stat)return false;const id=await resolveAthleteId(bet);if(!id)return false;const year=new Date().getFullYear(),path=bet.sport==="ncaaf"?"football/college-football":"football/nfl",league=bet.sport==="ncaaf"?"college-football":"nfl";const urls=[`https://site.web.api.espn.com/apis/common/v3/sports/${path}/athletes/${id}/overview`,`https://site.web.api.espn.com/apis/common/v3/sports/${path}/athletes/${id}/stats?season=${year}&seasontype=2`,`https://site.web.api.espn.com/apis/common/v3/sports/${path}/athletes/${id}/splits?season=${year}`,`https://sports.core.api.espn.com/v2/sports/football/leagues/${league}/seasons/${year}/types/2/athletes/${id}/statistics`,`https://site.web.api.espn.com/apis/common/v3/sports/${path}/athletes/${id}/gamelog`];let teamId=null,foundValue=null;for(const url of urls)try{const data=await getJson(url);teamId=teamId||teamIdFromData(data);let value=namedValue(data,bet.stat);if(value===null&&url.includes("gamelog"))value=sumGamelog(data,bet.stat);if(value!==null&&foundValue===null)foundValue=value}catch(_){}if(foundValue===null)return false;teamId=await resolveTeamId(path,id)||teamId;bet.current=foundValue;bet.espnAthleteId=id;bet.espnTeamId=teamId||bet.espnTeamId||null;const games=await teamGamesPlayed(path,bet.espnTeamId,year);if(games!==null)bet.teamGamesPlayed=games;bet.lastSync=new Date().toISOString();const target=Number(bet.target)||1;if((bet.status||"open")==="open"&&Number(bet.current)/target>=1)bet.status="hit";return true}
if(typeof module!=="undefined")module.exports={refreshPlayer,resolveAthleteId,resolveTeamId,teamGamesPlayed};if(typeof window!=="undefined")window.EspnPlayer={refreshPlayer,resolveAthleteId};
